services:
  # Backend API service
  - type: web
    name: olms
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://salestracker.github.io